apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
      - name: sales
        image: supermarket-project-sales-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5052
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
spec:
  selector:
    app: sales
  ports:
    - port: 5052
      targetPort: 5052
  type: NodePort